// NOTE: Models file name always start with captial letter
const mongoose = require("mongoose");
const { Schema } = mongoose;

const NotesSchema = new Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId, // type ObjectId, which is a unique identifier generated by MongoDB for each document. It's typically used as the primary key for documents in a MongoDB collection.
    ref: "users", // The ref property is used to establish a reference to another Mongoose model. In this case, the "user" field is referring to the "users" collection fron USER model.
  },
  title: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  tag: {
    type: String,
    default: "General",
  },
  date: {
    type: String,
    default: Date.now,
  },
});

module.exports = mongoose.model("notes", NotesSchema);
// "notes" is the collection name that will be made in mongo and will contain all stored notes
